const tools=[
{id:'qr',icon:'QR',name:'QR Code Generator',category:'Utility',description:'Create QR codes instantly from text or URLs.',keywords:'qr code generator url text'},
{id:'image-compressor',icon:'IC',name:'Image Compressor',category:'Image',description:'Compress images locally with quality control.',keywords:'image photo compressor canvas quality'},
{id:'image-resizer',icon:'IR',name:'Image Resizer',category:'Image',description:'Resize images with optional aspect ratio lock.',keywords:'image photo resize dimensions canvas'},
{id:'word-counter',icon:'WC',name:'Word Counter',category:'Writing',description:'Count words, characters, sentences and paragraphs live.',keywords:'word counter text writing characters sentences'},
{id:'json',icon:'{}',name:'JSON Formatter',category:'Developer',description:'Format, minify and validate JSON.',keywords:'json formatter minify validate developer'},
{id:'password',icon:'PW',name:'Password Generator',category:'Security',description:'Generate strong passwords in your browser.',keywords:'password generator random secure'},
{id:'base64',icon:'64',name:'Base64 Encoder / Decoder',category:'Developer',description:'Encode or decode Base64 text.',keywords:'base64 encode decode developer'},
{id:'url',icon:'URL',name:'URL Encoder / Decoder',category:'Developer',description:'Encode or decode URL-safe strings.',keywords:'url uri percent encode decode'},
{id:'uuid',icon:'ID',name:'UUID Generator',category:'Developer',description:'Generate one or many UUIDs.',keywords:'uuid guid random identifier'},
{id:'color',icon:'🎨',name:'Color Converter',category:'Design',description:'Convert colors between HEX, RGB and HSL.',keywords:'color converter hex rgb hsl picker'}];
const toolMap=Object.fromEntries(tools.map(t=>[t.id,t]));let activeTool=null;
function renderToolCards(){const grid=document.getElementById('toolGrid');grid.innerHTML=tools.map(t=>`<button class="tool-card" data-tool-id="${t.id}" data-search="${[t.name,t.description,t.category,t.keywords].join(' ').toLowerCase()}" aria-label="Open ${t.name}"><span class="tool-icon">${t.icon}</span><h3>${t.name}</h3><p>${t.description}</p><span class="tool-card-footer"><span>${t.category}</span><span>Open →</span></span></button>`).join('');grid.querySelectorAll('.tool-card').forEach(c=>c.addEventListener('click',()=>openTool(c.dataset.toolId)));}
function openTool(id){activeTool=id;const t=toolMap[id],ws=document.getElementById('workspace');document.getElementById('workspaceCategory').textContent=t.category;document.getElementById('workspaceTitle').textContent=t.name;document.getElementById('workspaceDescription').textContent=t.description;document.getElementById('workspaceBody').innerHTML=renderTool(id);ws.hidden=false;wireTool(id);ws.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>ws.focus(),350)}
function closeWorkspace(){document.getElementById('workspace').hidden=true;document.getElementById('workspaceBody').innerHTML='';activeTool=null;document.getElementById('tools').scrollIntoView({behavior:'smooth'});}
const copy=async text=>{try{await navigator.clipboard.writeText(text);return true}catch{return false}};
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function renderTool(id){return ({qr:qrHtml,'image-compressor':compressHtml,'image-resizer':resizeHtml,'word-counter':wordHtml,json:jsonHtml,password:passHtml,base64:codecHtml('Base64'),url:codecHtml('URL'),uuid:uuidHtml,color:colorHtml}[id])();}
function wireTool(id){({qr:wireQr,'image-compressor':wireCompress,'image-resizer':wireResize,'word-counter':wireWord,json:wireJson,password:wirePass,base64:()=>wireCodec('base64'),url:()=>wireCodec('url'),uuid:wireUuid,color:wireColor}[id])();}
function qrHtml(){return `<div class="tool-form"><div class="field"><label for="qrText">Text or URL</label><input id="qrText" placeholder="https://example.com"></div><div class="actions"><button class="button primary" id="qrGen">Generate QR Code</button><button class="button" id="qrDownload">Download</button><button class="button" id="qrCopy">Copy</button><button class="button ghost" id="qrReset">Reset</button></div><div id="qrPreview" class="qr-preview">QR Preview</div><p id="qrStatus" class="status"></p></div>`}
function wireQr(){let made=false;qrGen.onclick=()=>{qrPreview.innerHTML='';if(!qrText.value.trim())return qrStatus.textContent='Enter text or a URL first.';new QRCode(qrPreview,{text:qrText.value,width:220,height:220});made=true;qrStatus.textContent='QR code generated.'};qrDownload.onclick=()=>{const img=qrPreview.querySelector('img,canvas');if(!img||!made)return;if(img.tagName==='CANVAS')img.toBlob(b=>downloadBlob(b,'toolnest-qr.png'));else fetch(img.src).then(r=>r.blob()).then(b=>downloadBlob(b,'toolnest-qr.png'))};qrCopy.onclick=async()=>{const c=qrPreview.querySelector('canvas');if(!c)return; c.toBlob(async b=>{await navigator.clipboard.write([new ClipboardItem({'image/png':b})]);qrStatus.textContent='QR image copied.'})};qrReset.onclick=()=>{qrText.value='';qrPreview.innerHTML='QR Preview';qrStatus.textContent='';made=false}};
function compressHtml(){return `<div class="tool-form"><div class="field"><label>Upload image</label><input id="compFile" type="file" accept="image/*"></div><div class="range-row"><label for="compQuality">Quality</label><input id="compQuality" type="range" min=".1" max="1" step=".05" value=".75"><strong id="compQ">75%</strong></div><div class="actions"><button class="button primary" id="compBtn">Compress</button><button class="button" id="compDownload">Download compressed image</button></div><div class="stats"><div class="stat">Original<strong id="origSize">—</strong></div><div class="stat">Compressed<strong id="compSize">—</strong></div><div class="stat">Reduction<strong id="compRed">—</strong></div></div><div class="split"><div><p>Original</p><img id="compOrig" class="preview-img" alt="Original preview"></div><div><p>Compressed</p><img id="compOut" class="preview-img" alt="Compressed preview"></div></div></div>`}
function wireCompress(){let file,blob;compQuality.oninput=()=>compQ.textContent=Math.round(compQuality.value*100)+'%';compFile.onchange=()=>{file=compFile.files[0];if(file){origSize.textContent=fmt(file.size);compOrig.src=URL.createObjectURL(file)}};compBtn.onclick=()=>{if(!file)return;imgFrom(file).then(img=>{const c=canvas(img.width,img.height),x=c.getContext('2d');x.drawImage(img,0,0);c.toBlob(b=>{blob=b;compSize.textContent=fmt(b.size);compRed.textContent=Math.max(0,Math.round((1-b.size/file.size)*100))+'%';compOut.src=URL.createObjectURL(b)},'image/jpeg',+compQuality.value)})};compDownload.onclick=()=>blob&&downloadBlob(blob,'compressed.jpg')}
function resizeHtml(){return `<div class="tool-form"><div class="field"><label>Upload image</label><input id="resFile" type="file" accept="image/*"></div><div class="split"><div class="field"><label for="resW">Width</label><input id="resW" type="number" min="1"></div><div class="field"><label for="resH">Height</label><input id="resH" type="number" min="1"></div></div><div class="check"><input id="keepRatio" type="checkbox" checked><label for="keepRatio">Maintain aspect ratio</label></div><div class="actions"><button class="button primary" id="resBtn">Resize</button><button class="button" id="resDownload">Download</button></div><div class="split"><img id="resPreview" class="preview-img" alt="Uploaded preview"><img id="resOut" class="preview-img" alt="Resized preview"></div></div>`}
function wireResize(){let img,ratio=1,blob;resFile.onchange=async()=>{const f=resFile.files[0];if(!f)return;img=await imgFrom(f);ratio=img.width/img.height;resW.value=img.width;resH.value=img.height;resPreview.src=URL.createObjectURL(f)};resW.oninput=()=>{if(keepRatio.checked)resH.value=Math.round(resW.value/ratio)||''};resH.oninput=()=>{if(keepRatio.checked)resW.value=Math.round(resH.value*ratio)||''};resBtn.onclick=()=>{if(!img||!resW.value||!resH.value)return;const c=canvas(+resW.value,+resH.value),x=c.getContext('2d');x.drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{blob=b;resOut.src=URL.createObjectURL(b)},'image/png')};resDownload.onclick=()=>blob&&downloadBlob(blob,'resized.png')}
function wordHtml(){return `<div class="tool-form"><div class="field"><label for="wordText">Text</label><textarea id="wordText" placeholder="Start typing..."></textarea></div><div class="stats"><div class="stat">Words<strong id="wWords">0</strong></div><div class="stat">Characters<strong id="wChars">0</strong></div><div class="stat">No spaces<strong id="wNoSpaces">0</strong></div><div class="stat">Sentences<strong id="wSentences">0</strong></div><div class="stat">Paragraphs<strong id="wParas">0</strong></div></div></div>`}
function wireWord(){wordText.oninput=()=>{const v=wordText.value.trim();wChars.textContent=wordText.value.length;wNoSpaces.textContent=wordText.value.replace(/\s/g,'').length;wWords.textContent=v?v.split(/\s+/).length:0;wSentences.textContent=v?(v.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[]).length:0;wParas.textContent=v?v.split(/\n\s*\n/).filter(Boolean).length:0};}
function jsonHtml(){return `<div class="tool-form"><div class="field"><label for="jsonText">JSON</label><textarea id="jsonText" placeholder='{"hello":"Toolnest"}'></textarea></div><div class="actions"><button class="button primary" id="jsonFormat">Format</button><button class="button" id="jsonMin">Minify</button><button class="button" id="jsonVal">Validate</button><button class="button" id="jsonCopy">Copy</button><button class="button ghost" id="jsonClear">Clear</button></div><p id="jsonStatus" class="status"></p></div>`}
function wireJson(){const parse=()=>JSON.parse(jsonText.value);jsonFormat.onclick=()=>{try{jsonText.value=JSON.stringify(parse(),null,2);ok(jsonStatus,'Valid JSON formatted.')}catch(e){err(jsonStatus,e)}};jsonMin.onclick=()=>{try{jsonText.value=JSON.stringify(parse());ok(jsonStatus,'Valid JSON minified.')}catch(e){err(jsonStatus,e)}};jsonVal.onclick=()=>{try{parse();ok(jsonStatus,'Valid JSON.')}catch(e){err(jsonStatus,e)}};jsonCopy.onclick=()=>copy(jsonText.value).then(()=>ok(jsonStatus,'Copied.'));jsonClear.onclick=()=>{jsonText.value='';jsonStatus.textContent=''}}
function passHtml(){return `<div class="tool-form"><div class="field"><label for="passLen">Password length</label><input id="passLen" type="number" min="4" max="128" value="16"></div>${['Uppercase','Lowercase','Numbers','Symbols'].map((x,i)=>`<div class="check"><input id="pass${i}" type="checkbox" checked><label for="pass${i}">${x}</label></div>`).join('')}<div class="actions"><button class="button primary" id="passGen">Generate</button><button class="button" id="passCopy">Copy</button></div><div id="passOut" class="result-panel"></div></div>`}
function wirePass(){passGen.onclick=()=>{const sets=['ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz','0123456789','!@#$%^&*()_+-=[]{}|;:,.<>?'];let pool=sets.filter((_,i)=>document.getElementById('pass'+i).checked).join('');if(!pool)return passOut.textContent='Choose at least one character type.';const a=new Uint32Array(+passLen.value);crypto.getRandomValues(a);passOut.textContent=[...a].map(n=>pool[n%pool.length]).join('')};passCopy.onclick=()=>copy(passOut.textContent)}
function codecHtml(name){return()=>`<div class="tool-form"><div class="check"><input type="radio" name="mode" id="modeEnc" checked><label for="modeEnc">Encode</label><input type="radio" name="mode" id="modeDec"><label for="modeDec">Decode</label></div><div class="split"><div class="field"><label for="codeIn">Input</label><textarea id="codeIn"></textarea></div><div class="field"><label for="codeOut">Output</label><textarea id="codeOut" readonly></textarea></div></div><div class="actions"><button class="button primary" id="codeRun">Run ${name}</button><button class="button" id="codeCopy">Copy</button><button class="button ghost" id="codeClear">Clear</button></div><p id="codeStatus" class="status"></p></div>`}
function wireCodec(type){codeRun.onclick=()=>{try{codeOut.value=type==='base64'?(modeEnc.checked?btoa(unescape(encodeURIComponent(codeIn.value))):decodeURIComponent(escape(atob(codeIn.value)))):(modeEnc.checked?encodeURIComponent(codeIn.value):decodeURIComponent(codeIn.value));codeStatus.textContent='Done.';codeStatus.className='status success'}catch(e){err(codeStatus,e)}};codeCopy.onclick=()=>copy(codeOut.value);codeClear.onclick=()=>{codeIn.value=codeOut.value=codeStatus.textContent=''}}
function uuidHtml(){return `<div class="tool-form"><div class="field"><label for="uuidCount">How many?</label><input id="uuidCount" type="number" min="1" max="100" value="1"></div><div class="actions"><button class="button primary" id="uuidGen">Generate UUID</button><button class="button" id="uuidCopy">Copy</button><button class="button" id="uuidCopyAll">Copy all</button></div><div id="uuidOut" class="result-panel uuid-list"></div></div>`}
function wireUuid(){uuidGen.onclick=()=>{uuidOut.textContent=Array.from({length:Math.min(100,+uuidCount.value||1)},uuid).join('\n')};uuidCopy.onclick=()=>copy(uuidOut.textContent.split('\n')[0]||'');uuidCopyAll.onclick=()=>copy(uuidOut.textContent)}
function colorHtml(){return `<div class="tool-form"><div class="field"><label for="colorPick">Color picker</label><input id="colorPick" type="color" value="#2563eb"></div><div id="colorPreview" class="color-preview"></div><div class="copy-row"><code id="hexVal"></code><button class="button" data-copy-color="hexVal">Copy</button></div><div class="copy-row"><code id="rgbVal"></code><button class="button" data-copy-color="rgbVal">Copy</button></div><div class="copy-row"><code id="hslVal"></code><button class="button" data-copy-color="hslVal">Copy</button></div></div>`}
function wireColor(){const upd=()=>{const hex=colorPick.value,r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16),hsl=rgbToHsl(r,g,b);colorPreview.style.background=hex;hexVal.textContent=hex.toUpperCase();rgbVal.textContent=`rgb(${r}, ${g}, ${b})`;hslVal.textContent=`hsl(${hsl[0]}, ${hsl[1]}%, ${hsl[2]}%)`};colorPick.oninput=upd;document.querySelectorAll('[data-copy-color]').forEach(b=>b.onclick=()=>copy(document.getElementById(b.dataset.copyColor).textContent));upd()}
function fmt(n){return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(2)} MB`}function imgFrom(f){return new Promise(res=>{const i=new Image();i.onload=()=>res(i);i.src=URL.createObjectURL(f)})}function canvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c}function ok(el,msg){el.textContent=msg;el.className='status success'}function err(el,e){el.textContent='Error: '+e.message;el.className='status error'}function uuid(){return crypto.randomUUID?crypto.randomUUID():'10000000-1000-4000-8000-100000000000'.replace(/[018]/g,c=>(c^crypto.getRandomValues(new Uint8Array(1))[0]&15>>c/4).toString(16))}function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b);let h,s,l=(max+min)/2;if(max===min)h=s=0;else{const d=max-min;s=l>.5?d/(2-max-min):d/(max+min);h=max===r?(g-b)/d+(g<b?6:0):max===g?(b-r)/d+2:(r-g)/d+4;h/=6}return [Math.round(h*360),Math.round(s*100),Math.round(l*100)]}
